
package Vista;

/**
 *
 * @author Jhontabo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        lbl_acceso = new javax.swing.JLabel();
        lblI_IconUser = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        JText_Usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_Icon_user_small = new javax.swing.JLabel();
        lbl_Contraseña = new javax.swing.JLabel();
        lbl_Key_icon = new javax.swing.JLabel();
        JText_Contraseña = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnAceeder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(112, 145, 255));

        lbl_acceso.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lbl_acceso.setForeground(new java.awt.Color(255, 255, 255));
        lbl_acceso.setText("Acceso");

        lblI_IconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userInicio.png"))); // NOI18N

        lbl_usuario.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("Usuario:");

        JText_Usuario.setBackground(new java.awt.Color(112, 145, 255));
        JText_Usuario.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        JText_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        JText_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JText_Usuario.setBorder(null);
        JText_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JText_UsuarioActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        lbl_Icon_user_small.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userLabel.png"))); // NOI18N

        lbl_Contraseña.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lbl_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Contraseña.setText("Contraseña");

        lbl_Key_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/key.png"))); // NOI18N

        JText_Contraseña.setBackground(new java.awt.Color(112, 145, 255));
        JText_Contraseña.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        JText_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        JText_Contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JText_Contraseña.setBorder(null);
        JText_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JText_ContraseñaActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jbtnAceeder.setBackground(new java.awt.Color(60, 78, 234));
        jbtnAceeder.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnAceeder.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAceeder.setText("Iniciar sesión");
        jbtnAceeder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAceederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblI_IconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_usuario)))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_acceso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Icon_user_small, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(JText_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Key_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2)
                    .addComponent(JText_Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(81, 81, 81))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lbl_Contraseña)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jbtnAceeder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbl_acceso)
                .addGap(18, 18, 18)
                .addComponent(lblI_IconUser)
                .addGap(26, 26, 26)
                .addComponent(lbl_usuario)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JText_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Icon_user_small, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbl_Contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JText_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Key_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jbtnAceeder, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JText_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JText_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JText_UsuarioActionPerformed

    private void JText_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JText_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JText_ContraseñaActionPerformed

    private void jbtnAceederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAceederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAceederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JText_Contraseña;
    private javax.swing.JTextField JText_Usuario;
    private javax.swing.JPanel Panel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnAceeder;
    private javax.swing.JLabel lblI_IconUser;
    private javax.swing.JLabel lbl_Contraseña;
    private javax.swing.JLabel lbl_Icon_user_small;
    private javax.swing.JLabel lbl_Key_icon;
    private javax.swing.JLabel lbl_acceso;
    private javax.swing.JLabel lbl_usuario;
    // End of variables declaration//GEN-END:variables
}
