
package Vista;

import Modelo.Cliente;
import Modelo.ClienteDao;
import Modelo.Proveedor;
import Modelo.ProveedorDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhontabo
 */
public class Sistema extends javax.swing.JFrame {

    
    Cliente cl=new Cliente();
    ClienteDao client= new ClienteDao();
    Proveedor pr= new Proveedor();
    ProveedorDao prDao = new ProveedorDao();
    DefaultTableModel model= new DefaultTableModel();
    
    public Sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdCliente.setVisible(false);
    }
    
    public void ListarCliente(){
        List<Cliente> ListarCl=client.Listarcliente();
        model = (DefaultTableModel) TableCliente.getModel();
        Object [] ob = new Object[6];
        
        for(int i=0; i<ListarCl.size();i++){
            
            ob[0]=ListarCl.get(i).getId();
            ob[1]=ListarCl.get(i).getCedula();
            ob[2]=ListarCl.get(i).getNombre();
            ob[3]=ListarCl.get(i).getDireccion();
            ob[4]=ListarCl.get(i).getTelefono();
            ob[5]=ListarCl.get(i).getCorreo();
            model.addRow(ob);
            
        }
        
        TableCliente.setModel(model);
    }
    
    
      public void ListarProovedor(){
        List<Proveedor> ListarPr=prDao.ListarProveedor();
        model = (DefaultTableModel) TableProveedor.getModel();
        Object [] ob = new Object[6];
        
        for(int i=0; i<ListarPr.size();i++){
            
            ob[0]=ListarPr.get(i).getId();
            ob[1]=ListarPr.get(i).getRuc();
            ob[2]=ListarPr.get(i).getNombre();
            ob[3]=ListarPr.get(i).getDireccion();
            ob[4]=ListarPr.get(i).getTelefono();
            ob[5]=ListarPr.get(i).getCorreo();
            model.addRow(ob);
            
        }
        
        TableProveedor.setModel(model);
    }
    public void LimpiarTable(){
        for(int i=0;i<model.getRowCount();i++){
            model.removeRow(i);
            i=i-1;
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Vista1 = new javax.swing.JPanel();
        lbl_codigo = new javax.swing.JLabel();
        lbl_cantidad = new javax.swing.JLabel();
        lbl_precio = new javax.swing.JLabel();
        lbl_stockD = new javax.swing.JLabel();
        lbl_iconEliminar = new javax.swing.JLabel();
        JText_Codigo = new javax.swing.JTextField();
        JText_Cantidad = new javax.swing.JTextField();
        JText_StockD = new javax.swing.JTextField();
        JText_Precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Vista2 = new javax.swing.JPanel();
        lbl_nombreC = new javax.swing.JLabel();
        lbl_direccionC = new javax.swing.JLabel();
        lbl_telefonoC = new javax.swing.JLabel();
        lbl_correoC = new javax.swing.JLabel();
        jText_DireccionC = new javax.swing.JTextField();
        jText_CorreoC = new javax.swing.JTextField();
        jTex_NombreC = new javax.swing.JTextField();
        jText_TelefonoC = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableCliente = new javax.swing.JTable();
        btn_actualizarC = new javax.swing.JButton();
        btn_agregarC = new javax.swing.JButton();
        bnt_eliminarC = new javax.swing.JButton();
        lbl_cedulaC = new javax.swing.JLabel();
        jText_cedulaC = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        Vista3 = new javax.swing.JPanel();
        lbl_NombreP = new javax.swing.JLabel();
        lbl_telefonoP = new javax.swing.JLabel();
        lbl_direccionP = new javax.swing.JLabel();
        lbl_correoP = new javax.swing.JLabel();
        jTextNombreP = new javax.swing.JTextField();
        jTextTelefonoP = new javax.swing.JTextField();
        jTextDireccionP = new javax.swing.JTextField();
        jTextCorreoP = new javax.swing.JTextField();
        btn_agregarP = new javax.swing.JButton();
        btn_eliminarP = new javax.swing.JButton();
        btn_actualizarP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableProveedor = new javax.swing.JTable();
        jText_rucPr = new javax.swing.JTextField();
        lbl_ruc = new javax.swing.JLabel();
        txtIdProovedor = new javax.swing.JTextField();
        Vista4 = new javax.swing.JPanel();
        lbl_CodigoPr = new javax.swing.JLabel();
        lbl_TipoPr = new javax.swing.JLabel();
        lbl_cantidadPr = new javax.swing.JLabel();
        lbl_PrecioPr = new javax.swing.JLabel();
        lbl_nombrePr = new javax.swing.JLabel();
        jTextNombrePr = new javax.swing.JTextField();
        jTextTipoPr = new javax.swing.JTextField();
        jTextPrecioPr = new javax.swing.JTextField();
        jTextCantidadPr = new javax.swing.JTextField();
        jTextCodigoPr = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        btn_agregarPr = new javax.swing.JButton();
        btn_eliminarPr = new javax.swing.JButton();
        btn_actualizarPr = new javax.swing.JButton();
        BarraLateral = new javax.swing.JPanel();
        btn_nuevaVenta = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        btn_proovedores = new javax.swing.JButton();
        btn_productos = new javax.swing.JButton();
        lbl_encabezado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_codigo.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lbl_codigo.setText("Codigo");

        lbl_cantidad.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lbl_cantidad.setText("Cantidad");

        lbl_precio.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lbl_precio.setText("Precio");

        lbl_stockD.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        lbl_stockD.setText("Stock disponible");

        lbl_iconEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N

        JText_Precio.setEditable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        javax.swing.GroupLayout Vista1Layout = new javax.swing.GroupLayout(Vista1);
        Vista1.setLayout(Vista1Layout);
        Vista1Layout.setHorizontalGroup(
            Vista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vista1Layout.createSequentialGroup()
                .addGroup(Vista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Vista1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(JText_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JText_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Vista1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lbl_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Vista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Vista1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lbl_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vista1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JText_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)))
                .addGap(23, 23, 23)
                .addGroup(Vista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Vista1Layout.createSequentialGroup()
                        .addComponent(JText_StockD, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(lbl_iconEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_stockD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
            .addGroup(Vista1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        Vista1Layout.setVerticalGroup(
            Vista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vista1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(Vista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cantidad)
                    .addComponent(lbl_precio)
                    .addComponent(lbl_stockD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Vista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_iconEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Vista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JText_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JText_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JText_StockD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JText_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vista1", Vista1);

        lbl_nombreC.setText("Nombre :");

        lbl_direccionC.setText("Direccion :");

        lbl_telefonoC.setText("Telefono :");

        lbl_correoC.setText("Correo :");

        jText_TelefonoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_TelefonoCActionPerformed(evt);
            }
        });

        TableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CEDULA", "NOMBRE", "DIRECCION", "TELEFONO", "CORREO"
            }
        ));
        TableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableCliente);
        if (TableCliente.getColumnModel().getColumnCount() > 0) {
            TableCliente.getColumnModel().getColumn(0).setPreferredWidth(30);
            TableCliente.getColumnModel().getColumn(1).setPreferredWidth(30);
            TableCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
            TableCliente.getColumnModel().getColumn(3).setPreferredWidth(80);
            TableCliente.getColumnModel().getColumn(4).setPreferredWidth(50);
            TableCliente.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        btn_actualizarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/actualizar.png"))); // NOI18N
        btn_actualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarCActionPerformed(evt);
            }
        });

        btn_agregarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        btn_agregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarCActionPerformed(evt);
            }
        });

        bnt_eliminarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrar.png"))); // NOI18N
        bnt_eliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_eliminarCActionPerformed(evt);
            }
        });

        lbl_cedulaC.setText("cc :");

        javax.swing.GroupLayout Vista2Layout = new javax.swing.GroupLayout(Vista2);
        Vista2.setLayout(Vista2Layout);
        Vista2Layout.setHorizontalGroup(
            Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vista2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Vista2Layout.createSequentialGroup()
                        .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_correoC)
                            .addComponent(btn_agregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Vista2Layout.createSequentialGroup()
                                .addComponent(bnt_eliminarC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btn_actualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jText_TelefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jText_CorreoC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Vista2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTex_NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jText_DireccionC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jText_cedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(Vista2Layout.createSequentialGroup()
                        .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Vista2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lbl_telefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_direccionC, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Vista2Layout.setVerticalGroup(
            Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vista2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vista2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cedulaC)
                    .addComponent(jText_cedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreC)
                    .addComponent(jTex_NombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccionC)
                    .addComponent(jText_DireccionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_TelefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_telefonoC))
                .addGap(30, 30, 30)
                .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_CorreoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_correoC))
                .addGap(18, 18, 18)
                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_actualizarC)
                        .addComponent(btn_agregarC))
                    .addComponent(bnt_eliminarC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("Vista2", Vista2);

        lbl_NombreP.setText("Nombre :");

        lbl_telefonoP.setText("Telefono:");

        lbl_direccionP.setText("Direccion :");

        lbl_correoP.setText("Correo :");

        jTextTelefonoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefonoPActionPerformed(evt);
            }
        });

        btn_agregarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        btn_agregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPActionPerformed(evt);
            }
        });

        btn_eliminarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrar.png"))); // NOI18N
        btn_eliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarPActionPerformed(evt);
            }
        });

        btn_actualizarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/actualizar.png"))); // NOI18N
        btn_actualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarPActionPerformed(evt);
            }
        });

        TableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RUC", "NOMBRE", "TELEFONO", "DIRECCION", "CORREO"
            }
        ));
        TableProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProveedorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableProveedor);
        if (TableProveedor.getColumnModel().getColumnCount() > 0) {
            TableProveedor.getColumnModel().getColumn(0).setPreferredWidth(30);
            TableProveedor.getColumnModel().getColumn(1).setPreferredWidth(30);
            TableProveedor.getColumnModel().getColumn(2).setPreferredWidth(100);
            TableProveedor.getColumnModel().getColumn(3).setPreferredWidth(50);
            TableProveedor.getColumnModel().getColumn(4).setPreferredWidth(100);
            TableProveedor.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        lbl_ruc.setText("Ruc :");

        javax.swing.GroupLayout Vista3Layout = new javax.swing.GroupLayout(Vista3);
        Vista3.setLayout(Vista3Layout);
        Vista3Layout.setHorizontalGroup(
            Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vista3Layout.createSequentialGroup()
                .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_ruc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_direccionP, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addComponent(lbl_correoP, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                    .addComponent(btn_agregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_telefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Vista3Layout.createSequentialGroup()
                        .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Vista3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(btn_eliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_actualizarP, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Vista3Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(txtIdProovedor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Vista3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_rucPr, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTelefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDireccionP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCorreoP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addContainerGap())
        );
        Vista3Layout.setVerticalGroup(
            Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vista3Layout.createSequentialGroup()
                .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Vista3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_rucPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ruc))
                        .addGap(18, 18, 18)
                        .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_NombreP)
                            .addComponent(jTextNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_telefonoP)
                            .addComponent(jTextTelefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_direccionP)
                            .addComponent(jTextDireccionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCorreoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_correoP))
                        .addGap(31, 31, 31)
                        .addComponent(txtIdProovedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(Vista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_agregarP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_eliminarP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_actualizarP, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(Vista3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vista3", Vista3);

        lbl_CodigoPr.setText("Codigo :");

        lbl_TipoPr.setText("Tipo :");

        lbl_cantidadPr.setText("Cantidad :");

        lbl_PrecioPr.setText("Precio :");

        lbl_nombrePr.setText("Nombre :");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "TIPO", "PRECIO", "STOCK", "CODIGO"
            }
        ));
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable4.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable4.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable4.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable4.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        btn_agregarPr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar.png"))); // NOI18N
        btn_agregarPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarPrActionPerformed(evt);
            }
        });

        btn_eliminarPr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrar.png"))); // NOI18N

        btn_actualizarPr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/actualizar.png"))); // NOI18N

        javax.swing.GroupLayout Vista4Layout = new javax.swing.GroupLayout(Vista4);
        Vista4.setLayout(Vista4Layout);
        Vista4Layout.setHorizontalGroup(
            Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vista4Layout.createSequentialGroup()
                .addGroup(Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Vista4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_CodigoPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_nombrePr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_PrecioPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_TipoPr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_cantidadPr, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCantidadPr)
                            .addComponent(jTextCodigoPr)
                            .addComponent(jTextNombrePr, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTipoPr)
                            .addComponent(jTextPrecioPr))
                        .addGap(15, 15, 15))
                    .addGroup(Vista4Layout.createSequentialGroup()
                        .addComponent(btn_agregarPr, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminarPr, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_actualizarPr, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Vista4Layout.setVerticalGroup(
            Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Vista4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Vista4Layout.createSequentialGroup()
                        .addGroup(Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombrePr)
                            .addComponent(jTextNombrePr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TipoPr)
                            .addComponent(jTextTipoPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_PrecioPr)
                            .addComponent(jTextPrecioPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cantidadPr)
                            .addComponent(jTextCantidadPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CodigoPr)
                            .addComponent(jTextCodigoPr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(Vista4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_eliminarPr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_actualizarPr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_agregarPr))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vista4", Vista4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 890, 420));

        BarraLateral.setBackground(new java.awt.Color(89, 113, 231));
        BarraLateral.setForeground(new java.awt.Color(255, 255, 255));

        btn_nuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pago.png"))); // NOI18N
        btn_nuevaVenta.setText("Nueva Venta");

        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cliente.png"))); // NOI18N
        btn_clientes.setText("Clientes");
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        btn_proovedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mensajero.png"))); // NOI18N
        btn_proovedores.setText("Proveedor");
        btn_proovedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proovedoresActionPerformed(evt);
            }
        });

        btn_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Productos.png"))); // NOI18N
        btn_productos.setText("Productos");

        javax.swing.GroupLayout BarraLateralLayout = new javax.swing.GroupLayout(BarraLateral);
        BarraLateral.setLayout(BarraLateralLayout);
        BarraLateralLayout.setHorizontalGroup(
            BarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_nuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(btn_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_proovedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BarraLateralLayout.setVerticalGroup(
            BarraLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLateralLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btn_nuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_proovedores, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(BarraLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 490));

        lbl_encabezado.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        lbl_encabezado.setText("Punto de venta");
        getContentPane().add(lbl_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_TelefonoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_TelefonoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_TelefonoCActionPerformed

    private void btn_agregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarCActionPerformed
        // TODO add your handling code here:
        
        if (!"".equals(jText_cedulaC.getText()) ||!"".equals(jTex_NombreC.getText()) || !"".equals(jText_DireccionC.getText()) || !"".equals(jText_TelefonoC.getText()) || !"".equals(jText_CorreoC.getText())) {
       
            cl.setCedula(jText_cedulaC.getText());
            cl.setNombre(jTex_NombreC.getText());
            cl.setDireccion(jText_DireccionC.getText());
            cl.setTelefono(jText_TelefonoC.getText());
            cl.setCorreo(jText_CorreoC.getText());
            client.RegistrarCliente(cl);
            JOptionPane.showMessageDialog(null, "Cliente Registrado");
            LimpiarTable();     
            LimpiarCliente();
            ListarCliente();
            /*
            btnEditarCliente.setEnabled(false);
            btnEliminarCliente.setEnabled(false);
            btnGuardarCliente.setEnabled(true);*/
        } else {
            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
        }
    }//GEN-LAST:event_btn_agregarCActionPerformed

    private void jTextTelefonoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefonoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefonoPActionPerformed

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        // TODO add your handling code here:
       LimpiarTable();
       ListarCliente();
       jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void TableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClienteMouseClicked
        // TODO add your handling code here:
        
        int fila = TableCliente.rowAtPoint(evt.getPoint());
        
        txtIdCliente.setText(TableCliente.getValueAt(fila, 0).toString());
        jText_cedulaC.setText(TableCliente.getValueAt(fila, 1).toString());
        jTex_NombreC.setText(TableCliente.getValueAt(fila, 2).toString());
        jText_DireccionC.setText(TableCliente.getValueAt(fila, 3).toString());
        jText_TelefonoC.setText(TableCliente.getValueAt(fila, 4).toString());
        jText_CorreoC.setText(TableCliente.getValueAt(fila, 5).toString());
        
    }//GEN-LAST:event_TableClienteMouseClicked

    private void bnt_eliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_eliminarCActionPerformed
        // TODO add your handling code here:
        
        if(!"".equals(txtIdCliente.getText())){
            int pregunta = JOptionPane.showConfirmDialog(null,"Esta seguro de elimar");
            
            if(pregunta== 0){
                
                int id=Integer.parseInt(txtIdCliente.getText());
                client.EliminarCliente(id);
                ListarCliente();
                LimpiarTable();
                ListarCliente();
            }
        }else{
            JOptionPane.showMessageDialog(null,"Selecione una fila");
        }
        
    }//GEN-LAST:event_bnt_eliminarCActionPerformed

    private void btn_actualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarCActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtIdCliente.getText())){
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
        else{
           
            
            if (!"".equals(jText_cedulaC.getText()) ||!"".equals(jTex_NombreC.getText()) || !"".equals(jText_DireccionC.getText()) || !"".equals(jText_TelefonoC.getText()) || !"".equals(jText_CorreoC.getText())){
                
                cl.setCedula(jText_cedulaC.getText());
                cl.setNombre(jTex_NombreC.getText());
                 cl.setDireccion(jText_DireccionC.getText());
                cl.setTelefono(jText_TelefonoC.getText());
                cl.setCorreo(jText_CorreoC.getText());
                cl.setId(Integer.parseInt(txtIdCliente.getText()));
                
                client.ModificarCliente(cl);
                LimpiarTable();
                LimpiarCliente();
                ListarCliente();
            }else{
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btn_actualizarCActionPerformed

    private void btn_agregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPActionPerformed
        // TODO add your handling code here:
         if (!"".equals(jText_rucPr.getText()) ||!"".equals(jTextNombreP.getText()) || !"".equals(jTextDireccionP.getText()) || !"".equals(jTextTelefonoP.getText()) || !"".equals(jTextCorreoP.getText())){
             
                pr.setRuc(jText_rucPr.getText());
                pr.setNombre(jTextNombreP.getText());
                pr.setDireccion(jTextDireccionP.getText());
                pr.setTelefono(jTextTelefonoP.getText());
                pr.setCorreo(jTextCorreoP.getText());
                
                prDao.RegistrarProveedor(pr);
                
                LimpiarTable();
                ListarProovedor();
                LimpiarProveedor();
                JOptionPane.showMessageDialog(null, "Proveedor registrado");
         }else{
             JOptionPane.showMessageDialog(null, "los campos estan vacios");
         }
        
    }//GEN-LAST:event_btn_agregarPActionPerformed

    private void btn_proovedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proovedoresActionPerformed
        // TODO add your handling code here:
        ListarProovedor();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btn_proovedoresActionPerformed

    private void TableProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProveedorMouseClicked
        // TODO add your handling code here:
        
        int fila = TableProveedor.rowAtPoint(evt.getPoint());
        
        txtIdProovedor.setText(TableProveedor.getValueAt(fila, 0).toString());
        jText_rucPr.setText(TableProveedor.getValueAt(fila, 1).toString());
        jTextNombreP.setText(TableProveedor.getValueAt(fila, 2).toString());
        jTextDireccionP.setText(TableProveedor.getValueAt(fila, 3).toString());
        jTextTelefonoP.setText(TableProveedor.getValueAt(fila, 4).toString());
        jTextCorreoP.setText(TableProveedor.getValueAt(fila, 5).toString());
        
    }//GEN-LAST:event_TableProveedorMouseClicked

    private void btn_eliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarPActionPerformed
        // TODO add your handling code here:
         if(!"".equals(txtIdProovedor.getText())){
            int pregunta = JOptionPane.showConfirmDialog(null,"Esta seguro de elimar");
            
            if(pregunta== 0){
                
                int id=Integer.parseInt(txtIdProovedor.getText());
                prDao.EliminarProveedor(id);
                LimpiarTable();
                ListarProovedor();
                LimpiarProveedor();
            }
        }else{
             JOptionPane.showMessageDialog(null,"Selecione una fila");
         }
    }//GEN-LAST:event_btn_eliminarPActionPerformed

    private void btn_actualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarPActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtIdProovedor.getText())){
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
        else{
           
            
            if (!"".equals(jText_rucPr.getText()) ||!"".equals(jTextNombreP.getText()) || !"".equals(jTextDireccionP.getText()) || !"".equals(jTextTelefonoP.getText()) || !"".equals(jTextCorreoP.getText())){
                
                pr.setRuc(jText_rucPr.getText());
                pr.setNombre(jTextNombreP.getText());
                pr.setDireccion(jTextDireccionP.getText());
                pr.setTelefono(jTextTelefonoP.getText());
                pr.setCorreo(jTextCorreoP.getText());
                pr.setId(Integer.parseInt(txtIdProovedor.getText()));
                
                prDao.ModificarProveedor(pr);
                LimpiarTable();
                LimpiarProveedor();
                ListarProovedor();
            }else{
                JOptionPane.showMessageDialog(null, "Los campos estan vacios");
            }
        }
    }//GEN-LAST:event_btn_actualizarPActionPerformed

    private void btn_agregarPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarPrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarPrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraLateral;
    private javax.swing.JTextField JText_Cantidad;
    private javax.swing.JTextField JText_Codigo;
    private javax.swing.JTextField JText_Precio;
    private javax.swing.JTextField JText_StockD;
    private javax.swing.JTable TableCliente;
    private javax.swing.JTable TableProveedor;
    private javax.swing.JPanel Vista1;
    private javax.swing.JPanel Vista2;
    private javax.swing.JPanel Vista3;
    private javax.swing.JPanel Vista4;
    private javax.swing.JButton bnt_eliminarC;
    private javax.swing.JButton btn_actualizarC;
    private javax.swing.JButton btn_actualizarP;
    private javax.swing.JButton btn_actualizarPr;
    private javax.swing.JButton btn_agregarC;
    private javax.swing.JButton btn_agregarP;
    private javax.swing.JButton btn_agregarPr;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_eliminarP;
    private javax.swing.JButton btn_eliminarPr;
    private javax.swing.JButton btn_nuevaVenta;
    private javax.swing.JButton btn_productos;
    private javax.swing.JButton btn_proovedores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTex_NombreC;
    private javax.swing.JTextField jTextCantidadPr;
    private javax.swing.JTextField jTextCodigoPr;
    private javax.swing.JTextField jTextCorreoP;
    private javax.swing.JTextField jTextDireccionP;
    private javax.swing.JTextField jTextNombreP;
    private javax.swing.JTextField jTextNombrePr;
    private javax.swing.JTextField jTextPrecioPr;
    private javax.swing.JTextField jTextTelefonoP;
    private javax.swing.JTextField jTextTipoPr;
    private javax.swing.JTextField jText_CorreoC;
    private javax.swing.JTextField jText_DireccionC;
    private javax.swing.JTextField jText_TelefonoC;
    private javax.swing.JTextField jText_cedulaC;
    private javax.swing.JTextField jText_rucPr;
    private javax.swing.JLabel lbl_CodigoPr;
    private javax.swing.JLabel lbl_NombreP;
    private javax.swing.JLabel lbl_PrecioPr;
    private javax.swing.JLabel lbl_TipoPr;
    private javax.swing.JLabel lbl_cantidad;
    private javax.swing.JLabel lbl_cantidadPr;
    private javax.swing.JLabel lbl_cedulaC;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_correoC;
    private javax.swing.JLabel lbl_correoP;
    private javax.swing.JLabel lbl_direccionC;
    private javax.swing.JLabel lbl_direccionP;
    private javax.swing.JLabel lbl_encabezado;
    private javax.swing.JLabel lbl_iconEliminar;
    private javax.swing.JLabel lbl_nombreC;
    private javax.swing.JLabel lbl_nombrePr;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_ruc;
    private javax.swing.JLabel lbl_stockD;
    private javax.swing.JLabel lbl_telefonoC;
    private javax.swing.JLabel lbl_telefonoP;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProovedor;
    // End of variables declaration//GEN-END:variables
    private void LimpiarCliente() {
        txtIdCliente.setText("");
        jText_cedulaC.setText("");
        jTex_NombreC.setText("");
        jText_DireccionC.setText("");
        jText_TelefonoC.setText("");
        jText_CorreoC.setText("");
    }
    
    private void LimpiarProveedor() {
        txtIdProovedor.setText("");
        jText_rucPr.setText("");
        jTextNombreP.setText("");
        jTextDireccionP.setText("");
        jTextTelefonoP.setText("");
        jTextCorreoP.setText("");
    }

    
}
